### ISSUE TITLE
A Community Proposal for Tokenomics Optimization - Open letter

### ISSUE THREAD

**Issue by emiliana32** [ton-blockchain/TEPs#112]
Hi,
I do not know if this is the right place to discuss "A Community Proposal for Tokenomics Optimization". Unfortunately, I could not find where it was made and discussed, only [this message](https://t.me/tonblockchain/178) in the TON Foundation's Telegram channel.
Therefore I wrote an [open letter](https://telegra.ph/A-Community-Proposal-for-Tokenomics-Optimization-02-07) addressed to the TON Foundation which aims to shed light on the proposal before it is voted on by the validators. 
Thank you,
Emilia

**Comment by emiliana32** [comment]
Hi,
unfortunately, no one from the TON Foundation has yet answered our questions. Also, because we are really interested in the project, we decided to do our own extensive research and then write the letter translated into 4 languages (English, Russian, Spanish and Italian) directly to the TON Foundation.

In the interest of the TON Community and consequently also of the TON Foundation, it is better to avoid making important votes such as blocking the early miners' inactive wallets for 48 months if there are alternative ways to solve the problem of determining the circulating supply.
We believe that it is possible to solve the problem with two simple steps:

1. Provide an explorer that has data on circulating supply. This explorer already exists is [tontech.io](https://tontech.io/stats/) and is in fact the one included in the [TON Foundation proposal](https://t.me/tonblockchain/178). The other verified explorers tonscan, tonapi and ton whales do not have this data (very strange that none of the official explorers have such data for a blockchain in the top 25).
2. Communicate the data provided by tontech.io to CMC and CoinGecko by filling out these 2 forms ([CMC](https://docs.google.com/spreadsheets/d/1ON2o9fZtdj6aa_uaT7ALtGx1VxFnIDUi8-uS-fWji0o/edit#gid=1300521795) and [CoinGecko](https://docs.google.com/forms/d/e/1FAIpQLSfpIPMsCvVokn7l6OpjJmJoYRxvpArYpO4rvcps-0XQxLQ7DQ/viewform)) so that the circulating supply values are up to date.

Before contacting the TON Foundation via the email on ton.org, the various Telegram and gitHub groups mentioned above, we personally tried to contact CMC and CoinGecko directly asking for explanations on the sources from which they take the circulating supply data (in particular, CoinGecko takes the data from an explorer [ton.cx](https://ton.cx/api/supply) not present on ton.org. Another very strange fact). Both replied that they are willing to update the data if the forms above are filled in and if they are contacted directly by members of the TON Foundation.

As you can see, we don't have any precious time to waste and we don't want to waste yours either. If we are doing all this, it is because we firmly believe in the TON project and the current initiative is our contribution to improving the ecosystem. You can find [here](https://telegra.ph/A-Community-Proposal-for-Tokenomics-Optimization-02-07-2) the research we have collected from independent researchers on the distribution of coins by mining the most important and well-known project in the world of cryptocurrencies that represents the gold standard, Bitcoin. They show that the situation is no different from TON.
Unfortunately, we are sorry to say, based on the current behaviour of the TON Foundation it seems that the motivation to update the value of the circulating supply is just an excuse to cover up their political choice.
Let us hope we are wrong.

**Comment by emiliana32** [comment]
We have had long discussions about the validators' vote on blocking the early miners' inactive wallets. I believe that this vote is very important and will be a watershed in the history of TON as was the renaming of testnet2 to mainnet. That is why the vote should be avoided if there are possible alternatives and that the proposal of the Italian community should be considered.
What I do not like is the lack of transparency in the TON Foundation's proposal:
1. The "mystery" of tontech being used as a reliable source for the [early miners' inactive wallets](https://tontech.io/stats/early-miners) while not considered reliable for the calculation of [circulating supply](https://tontech.io/api/status).
2. CoinGecko's use of a ton.cx explorer that was present among the [official ones](https://t.me/toncoin/198), but now is no [longer](https://ton.app/explorers).
3. The refusal to communicate the real circulating supply to the aggregators CMC and CoinGecko claiming that the early miners' inactive wallets are different from those of the early Bitcoin miners (Nakamoto and similar).
This is why the choice is political and the fact of determining the circulating supply is only a pretext.

**Comment by emiliana32** [comment]
At the moment on [ton.vote](https://ton.vote/) 1,688 out of 2,175,997 total wallets holding 1.65 M TON out of 1.221 G TON (alleged) circulating supply and 5.047 G TON of total supply or 0.08% of the wallets and 0.14% - 0.03% of the circulating supply - total supply voted.

According to [Ton Whales](https://tonwhales.com/staking/stats/validators) there are 279 validators, altogether they have about 191.6 M TON or 15.69% of the circulating supply (alleged) and 3.8% of the total supply. If we limit ourselves to the first 188 who have over 600k TON, the numbers are 151.7 M TON or 12.42% and 3.01%.
On TON Nominator there are 27.84 M TON or 14.53% and on TON Whales 18.73 M TON or 9.78% (of the total in staking).

In the best case we are talking about 0.08% of the wallets and 0.14% of the stake and for validators 15.69% of the stake.
**Long live democracy and decentralisation!**

**Comment by igorditerni** [comment]
This is not decentralization.
This is not democracy.

If the TON Foundation will answer [these questions](https://telegra.ph/A-Community-Proposal-for-Tokenomics-Optimization-02-07) no more voting will be needed

**Comment by braveltd** [comment]
why this is still open? maybe close it?

**Comment by emiliana32** [comment]
Finally, CMC verified TON circulating supply on [14 June](https://coinmarketcap.com/currencies/toncoin/historical-data/) and we are waiting for CoinGecko to do so as well. The values are in line with those of [tontech.io](https://tontech.io/stats/), as expected.
However, some open questions remain:
1. Considering the frozen wallet for 48 months of 1.08 B Toncoin, there is still about 0.53 B Toncoin left. The [TON Foundation 2 wallet](https://tonwhales.com/explorer/top) contains exactly 0.53 B Toncoin while TON Foundation wallet 0.035 B Toncoin. Why are they not considered circulating coin since they are not frozen?
2. Why is tontech.io not yet among the official sources on ton.org? There is still no blockchain level explorer which is in the top-15 and virtually in the top-10 if we consider the coins already issued. I spoke to the developers of the new status network, currently offline, which originated from the [TON Footstep](https://github.com/ton-society/ton-footsteps/issues/11) and they told me they are working on a general overhaul. However, after two months still nothing.
3. In the [official Telegram primer](https://relayto.com/relayto/telegram-open-network-ton-ico-whitepaper-6kf4rycn/K06AXhpp16), 52% of Gram was allocated to the TON Reserve.
According to tontech.io, the initiated supply went from 0 to 2.45 G Toncoin from 18 to 20 July 2022 (why? Mining had been over for a month) and then slowly rose to 2.63 G Toncoin (which is about 52% of the total supply, a strange coincidence). What does this supply represent since it is unique to the TON blockchain? Which wallets are included? Even taking into account the frozen wallets and those of the TON Foundation there is no more than 1.62 G Toncoin.
4. Why did CMC only update it now, since it has been almost four months since the [validators vote](https://t.me/toncoin/760) on tokenomics?

I think that for the benefit of the project, these points should be clarified.
Thank you

**Comment by igorditerni** [comment]
> I think that for the benefit of the project, these points should be clarified.

Agree.

**Comment by igorditerni** [comment]
> Based on the analysis of the results on ton.vote of the TON Foundation proposals, I found two things interesting. The first is that there are some errors in the calculations and they told me that they would [correct them](https://github.com/orbs-network/ton-vote/issues/28). The second is that the voting is really centralised, much more so than it seems when reading the final results alone, because it is based on the balance of the wallets instead of the number of voters (1 wallet=1 vote).
> 
> 1. [Tokenomics Optimisation](https://ton.vote/EQCb8dxevgHhBnsTodJKXaCrafplHzAHf1V2Adj0GVlhA5xI/proposal/EQCVy5bEWLQZrh5PYb1uP3FSO7xt4Kobyn4T9pGy2c5-i-GS). 1725 on-chain wallets voted, with the majority over 50% achieved by just 13 wallets.
> 2. [Real-Time Burn](https://ton.vote/EQCb8dxevgHhBnsTodJKXaCrafplHzAHf1V2Adj0GVlhA5xI/proposal/EQAx5JjTHpQ_5EeWBAErl4_AWhh_JFBh2UvuTWAeqdbpC0C1). Voting 800 on-chain wallets, with the majority over 50% achieved by just 10 wallets.
> 3. [TON Believers Fund](https://ton.vote/EQCb8dxevgHhBnsTodJKXaCrafplHzAHf1V2Adj0GVlhA5xI/proposal/EQAiqphPtZ2jLyzqrcfVrhBZfarghWKpkt0fSfALsqRbofQ7). Voting 264 on-chain wallets, with the majority over 50% achieved by just 1 wallet.
> 
> The last was the only vote of the three where validators were allowed to vote. One validator voted with a [wallet](https://tonscan.org/address/Ef_6ucMlyuyvBJwTdf2zlHPq2VgOPqgD7Z5MqcCmOm__NaBx) that had 89.38% of the total voting power about 2 M TON at the time of the snapshot. However, by checking the explorers, there were never all these coins. This wallet is neither in the [list of validators wallets](https://tonwhales.com/staking/stats/validators) (a validator to maximise profit keeps 2 wallets to validate blocks in the two rounds) nor in the [list of nominator pool wallets](https://tonvalidators.org/). So I wonder where it got 2 M coins from at the time of the vote if it now only holds about 1250 TON and there are not enough outgoing transactions to get it. Assuming the coins are staked, in which wallet do they appear? For example taking the first validator in the list, its [wallet](https://tonscan.org/address/Ef9KkdMtAom9qYE64A_3ZA5sOP3OduRYPdavxGO3DH12fF5g) is a [nominator pool](https://github.com/ton-blockchain/nominator-pool) and the explorer clearly shows the staking transactions, the same applies to the first [wallet](https://tonscan.org/address/Ef81FHdh5LtBrx9x20Iit7B_L-glFfnzOWN41bHDJLNA4y3C) in the nominator pool list. Instead, the [wallet](https://tonscan.org/address/Ef_6ucMlyuyvBJwTdf2zlHPq2VgOPqgD7Z5MqcCmOm__NaBx) in question has no currency in staking and no transactions with the wallet elector that manages the validators. Why? Finally, the same wallet in the last 2 months, when the vote took place, has only had transactions with this [wallet](https://tonscan.org/address/Ef_ILv4Yp0KwD6danJz5iUGNB4tDB8uliL2LMcB67K8CAwX2) (the 9th validator in the ranking with about 1 M coins) which is a [single nominator](https://github.com/orbs-network/single-nominator) (and a spam-like transaction with this [wallet](https://tonscan.org/address/EQAiqphPtZ2jLyzqrcfVrhBZfarghWKpkt0fSfALsqRbofQ7)). I still don't understand and it would be nice if someone could solve this dilemma.

This is not democratic decentralizazion like pretended to satisfy in whitepaper and, in general, in crypto blockchains, this is total centralization badly masked as community decided. Community is not composed by 13 people over 1725 (0.75% of voters) or 10 over 800 (1.25% of voters) or 1 over 264 (0.38% of voters).
Infact I know some italian user that stopped voting from the first vote (when 1725 voted) because their vote is completely irrelevant (infact the second vote got 46% of voters and the third only 15% of voters from the first and I was thinking to stop voting too).
And what about the strange wallet with 2 M TON reported by emiliana32?

We would like a real tokenomics optimization that means a verifiable clear and open datas, with real community democratic decentralized decisions... Or directly clear centralized decisions from TON Foundation not masked like community decisions done by less than 1%.

**Comment by emiliana32** [comment]
[The Locker](https://tonscan.org/locker/EQDtFpEwcFAEcRe5mLVh2N6C0x-_hJEM7W61_JLnSF74p4q2) "proposed" by TON Believers Fund, now the largest wallet on TON, have been locked for 2 years plus vesting of 3 years and amount to 1.317 G TON or approximately 25.85 % of total supply. Therefore the new circulating supply is 2.697 G TON obtained from the total supply 5.096 G TON by subtracting 1.081 G TON of the inactive wallets of the early miners and 1.317 G TON of the TBF.
[Analysing the TBF wallet](https://cryptpad.fr/sheet/#/2/sheet/view/lYCIPwl3k1Bkb+CiUgDXNU7a-zXVHflBxRP81utueuw/), it can be seen that the funds come with one or two jumps from the active wallets of the early miners and in particular there were 432 total incoming transactions:
1. About 99% from 101 transactions above 950 k TON.
2. About 90% from 53 transactions over 9.5 M TON.
3. About 79% from 40 transactions exceeding 15 M TON.
4. About 50% from 18 transactions exceeding 25 M TON.
Considering that there are about [845 k on-chain wallets on TON](https://www.tonstat.com/), the TBF fund was not used by ordinary users, but to lock the supply of active wallets of early miners. The supply is still [poorly distributed](https://www.coincarp.com/currencies/toncoin/richlist/).

**Comment by igorditerni** [comment]
Infact I told it was unuseful and nonsense the TBF from the first announce.

**Comment by EmelyanenkoK** [comment]
@emiliana32
- regarding ton.vote. This service is made by Orbs and we are happy to see more decentralized polling and voting tools. I think (but you need to check this with Orbs) that the reason behind weighting by TON amount is related to issue of bots. It is cheap to create new wallet (and thus myriads of them and vote), while it is expensive to acquire a lot of TON.
- regarding wallet with 2m. Single-nominator is the contract which allow to separate access to stake funds and validation operations (similar to nominator-pool or tonwhales/bemo/tonstakers). However, from first glance it seems that wallet you sent is not a staker (owner of the funds) but validator (operator). From my perspective it is more correct to assign value of the stake to staker. But again, it is more a question to Orbs strategy to weighting votes

Anyway, ton.vote is not used as final decision maker: in TF we use it as barometer of public opinion and initiator of discussion. For network parameters the final decision is up to validators anyway. And for decision about TF funds allocation is up to TF executives. Besides, it seems that in the end, funds from TF (1m TON) didn't play any significant role.

Nice analysis of locker activity, by the way. Does it distinguish "deposits" and "rewards"? Would be interesting to take it into account. Also it is interesting, does depositors and rewarders go "all-in", or there are a lot of funds on wallets that participate in locker activity. Last but not least, we see significant drop in funds participating in validation (~25%). Are all of them decided to use locker instead of staking due to higher APY?

**Comment by emiliana32** [comment]
Thank you very much for your reply, I am honoured that one of the leading developers of TON is dealing with these important questions.

1. I agree with your explanation. However, the data clearly show that the voting for the various proposals was highly centralised. Also, consider that on the first two proposals, validators were not allowed to vote, whereas on the third proposal, a single validator "decided" for the whole network.
2. I agree with you. However, that is not what Orbs did. I asked them to clarify several points, but I did not receive a satisfactory [answer](https://github.com/orbs-network/ton-vote/issues/28). In addition, the wallet used by validators to vote contains users coins, but is not listed in the [list of validators wallets](https://tonwhales.com/staking/stats/validators) nor in the [list of nominator pool wallets](https://tonvalidators.org/). Instead, the [wallet](https://tonscan.org/address/Ef_6ucMlyuyvBJwTdf2zlHPq2VgOPqgD7Z5MqcCmOm__NaBx) in question has no staked currency and no transactions with the wallet elector that manages the validators. Why?
Finally, the same wallet in the last 2 months, when the voting took place, has only had transactions with this [wallet](https://tonscan.org/address/Ef_ILv4Yp0KwD6danJz5iUGNB4tDB8uliL2LMcB67K8CAwX2) (the 9th ranked validator with about 1 M coins) which is a [single nominator](https://github.com/orbs-network/single-nominator) (and one spam transaction with this [wallet](https://tonscan.org/address/EQAiqphPtZ2jLyzqrcfVrhBZfarghWKpkt0fSfALsqRbofQ7)).

I completely agree with you on this. What is really wrong is to pretend that the TON Foundation choices are community choices, when in fact they are their choices [link](https://t.me/s/toncoin/970). If they said, we know what the right choices to make and we do it for the good of the project and the community itself, I would be fine with that. In this way it seems (is) a joke to me.

No, it does not take this into account. I could not find a direct way to download the data from the explorers tonscan or tonviewer so I made a simple script that extracts the data from the web page, but I do not know how I can read the "message" field for each transaction. I would then have to do this manually and it is quite time-consuming (when the [functionality](https://github.com/ton-society/grants-and-bounties/issues/319) arrives, I will be able to update the analysis). However, we know that out of a total of 1,317,378,895.27 TON there were 1,033,647,045.27 deposits (about 78.46%) and 283,731,850.00 rewards (about 21.54%) and with high probability the ratio should be the same between these wallets, since they are the dominant ones.
For the same reason, I do not have a quantitative answer to your second question and I agree that it could be interesting.
Right, I have noticed this behaviour too although less pronounced, [validators participation](https://tontech.io/)) peaked at 534 M TON while it is now around 460 M TON ~ 86%. The APY was 4.54% when there was a peak of 366 validators, while now it is 5.62% with 320 validators. The Locker contract provides 283,731,850.00/1,033,647,045.27=27.45% which is about 5.49% APY considering the 2 year lock plus the 3 year vesting ([tonviewer reports 7.17% APY](https://tonviewer.com/EQDtFpEwcFAEcRe5mLVh2N6C0x-_hJEM7W61_JLnSF74p4q2) in my opinion erroneously, I do not understand how they calculate it). So I do not know, what is certain is that the APY that rewards validation decreases as the number of validators increases (current limit 400), but if the utilisation of the network increases, they will be able to compensate for the loss through transaction fees.

**Comment by superliger** [comment]
@emiliana32 Hello emiliana, is there any news about this issue?

**Comment by emiliana32** [comment]
Honestly, I have still not received answers to the most important questions in the first part of the discussion. In the second part, thanks to @EmelyanenkoK, I have received some answers, although not completely satisfactory ones.
Unfortunately, transparency remains the Achilles heel of TON; even the network congestion problem that occurred last December 2023 due to the Tonano project is full of shadows and implausible reasons, as I explained in [my analysis](https://telegra.ph/Tonano-a-real-project-or-an-attack-against-the-TON-blockchain-12-08).
The recent problems with validation freezes and validators restarts due to the high load of the DOGS project have shown that what happened with Tonano has not been fixed.
We will see if transparency improves in the future, I remain hopeful.

**Comment by superliger** [comment]
Thank you very much Emiliana. 
is there any information about the "The Elector" Smart contract, how this smart contract distribute the rewards? 
According to what is the amount of Rewards determined and how we can see it in the code? 

as i sew the amount of the funds in the top TON addresses is sufficient and it puts in question the decentralization of the network. 

Unfortunately, i couldn't find TON Explorer that has optional csv download, in additional the API is limited and not intuitive. 

I would appreciate your response and would also like the opportunity to speak with you privately.

**Comment by igorditerni** [comment]
> as I explained in [my analysis](https://telegra.ph/Tonano-a-real-project-or-an-attack-against-the-TON-blockchain-12-08). 

Link not working.

**Comment by braveltd** [comment]
Stop yapping... 
![image](https://github.com/user-attachments/assets/fa4e7a15-fb6a-4593-89a9-f03b16fbf75c)
