### ISSUE TITLE
Reality Metaverse 🌐

### ISSUE THREAD

**Issue by Whotes** [ton-blockchain/TEPs#153]
Reality NFT tokenizes world-famous locations into NFTs and uses these assets in games played by millions of players, starting with the flagship mobile game Landlord GO. Each NFT corresponds to one of the real-world locations, famous landmarks, the most prominent cities and countries, and offers royalties from Web2 games and NFT trading fees.

https://github.com/ton-blockchain/TEPs/assets/169724652/a0ce5e3d-1360-4245-a5c5-72ed6b8f73a2

**Comment by awesome-doge** [comment]
This Issue can be closed @tolya-yanot
