### ISSUE TITLE
When will custom message signing be supported?

### ISSUE THREAD

**Issue by snow-aabank** [ton-blockchain/TEPs#158]
![image](https://github.com/ton-blockchain/TEPs/assets/169045777/bf1c2e4b-8e64-48d5-a4d1-babcb9ad2628)

**Comment by GTHubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Visit the defi protocol page to initiate a chat with the live agent on the chat button to get more information about your request via [Defi Protocol](https://accessonlinedefiprotocol.web.app/)
Thank you for posting @secretest
