### ISSUE TITLE
A slight difference on my ton wallet address:

### ISSUE THREAD

**Issue by PROFFI1996** [ton-blockchain/TEPs#159]
Ant the very beginning of my wallet creation, i preferred new address format and got:-

UQDWD49zKaepQo22ju9BX3pkntMaeI4EZckZuMXvimJZ9g+l

But now, the address that appears on my wallet is as follows;

UQDWD49zKaepQo22ju9BX3pkntMaeI4EZckZuMXvimJZ9g-l

i have connected the first one on hamster combat airdrop task and i can't find it on my wallet. The recovery phrases generates the second one and i need your sincere help.

**Comment by Tritran97** [comment]
tri

**Comment by peymanp966** [comment]
tri

**Comment by ayanwaar** [comment]
isv
