### ISSUE TITLE
Hamster kombot

### ISSUE THREAD

**Issue by Winthamoe** [ton-blockchain/TEPs#170]
![-5785393653374632637_120](https://github.com/ton-blockchain/TEPs/assets/174960878/68e8e88f-8589-4529-b612-60cce5785653)

**Comment by Sweetmind300** [comment]
Can you please provide more details about this issue?

**Comment by DompetRahman** [comment]
Itu adalah hadiah dari give away saya

**Comment by DompetRahman** [comment]
> ![-5785393653374632637_120](https://private-user-images.githubusercontent.com/174960878/346355462-68e8e88f-8589-4529-b612-60cce5785653.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MTU4MTYsIm5iZiI6MTcyMTcxNTUxNiwicGF0aCI6Ii8xNzQ5NjA4NzgvMzQ2MzU1NDYyLTY4ZThlODhmLTg1ODktNDUyOS1iNjEyLTYwY2NlNTc4NTY1My5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyM1QwNjE4MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yY2E3NjU4MTE1ODg0Nzk3MjYzMjgwZjQwNmQ4OTk0NTVkNWIwMDNmN2IwM2ZmZTI2MzgwMDU4MTY0NmQ2NmVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.95dkenxKByGhAV5ErsuUFss6-BWl_6CHHlna2xG2jpI)
