### ISSUE TITLE
Unable to send transaction in Angular app

### ISSUE THREAD

**Issue by dsurya-rocketx** [ton-blockchain/TEPs#184]
Hey,

I am trying to send transaction for native and jettons also i have a provider but transaction is not happening. it's throwing error, Error: Connect wallet to send a transaction.
    at TonConnectUI.<anonymous>
    
    const tx = await this.provider.sendTransaction({
			messages: [
				{
					address: to, // destination address
					amount: amount * (10 ** token.token_decimals) //Toncoin in nanotons
				}
			]
		});

const body = beginCell()
				.storeUint(0xf8a7ea5, 32)  
				.storeUint(0, 64)          
				.storeCoins(amountInMinimalUnits)  
				.storeAddress(Address.parse(to))
				.storeAddress(Address.parse(this.activeWallet)) 
				.storeUint(0, 1)           
				.storeCoins(toNano('0.01')) 
				.storeUint(0, 1)           
				.endCell();

			const tx = await this.provider.sendTransaction({
				validUntil: Math.floor(Date.now() / 1000) + 360,
				messages: [
					{
						address: this.activeWallet,  
						amount: toNano('0.05').toString(), 
						payload: body.toBoc().toString('base64')
					}
				]
			});

**Comment by laalauren1** [comment]
@dsurya-rocketx You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID TON07638
Please see the link below to our dedicated support line:
[Toincoin live support](https://thedappsupport.web.app)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent
