### ISSUE TITLE
Money problem 

### ISSUE THREAD

**Issue by Danishboss0786** [ton-blockchain/TEPs#199]
Please support 🙏

**Comment by Lazarovv** [comment]
I exchanged 1,000,000 coins, will I receive them in my wallet?
UQAb2pi_4dMKnbKs0RS3AkjBjlm3mwIi3N_YxcrwvvxkOSAK

**Comment by Jomossey** [comment]
@Lazarovv When you exchange 1,000,000 coins, you should receive them in your wallet. The timing of when you'll receive them can vary depending on the exchange platform you used and the specific process they follow for transactions.
