### ISSUE TITLE
Wrong address 

### ISSUE THREAD

**Issue by Softtouch1200** [ton-blockchain/TEPs#201]
I mistakenly send 4049 dogs to a wrong ton address that was changed few days ago today around 01:11am,here is the address UQAt7-_FAYNpBHRyngHs25wfRXJBXJxtfQKaAZnQs5gd0F9E please help me refund it to my address. Thanks
![8DB84069-C231-4D76-8AAE-F1AD2C0FD00A](https://github.com/user-attachments/assets/6726f0d3-00e3-4d9a-bcc5-ef9d96470341)

**Comment by phyllis-sy** [comment]
> I mistakenly send 4049 dogs to a wrong ton address that was changed few days ago today around 01:11am,here is the address UQAt7-_FAYNpBHRyngHs25wfRXJBXJxtfQKaAZnQs5gd0F9E please help me refund it to my address. Thanks ![8DB84069-C231-4D76-8AAE-F1AD2C0FD00A](https://private-user-images.githubusercontent.com/181199065/366344904-6726f0d3-00e3-4d9a-bcc5-ef9d96470341.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYwNjMwNjEsIm5iZiI6MTcyNjA2Mjc2MSwicGF0aCI6Ii8xODExOTkwNjUvMzY2MzQ0OTA0LTY3MjZmMGQzLTAwZTMtNGQ5YS1iY2M1LWVmOWQ5NjQ3MDM0MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMVQxMzUyNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNTMwY2RlOGY3ZTE2MmQzZDliNzdkM2JlNzU0MGUzMjA3YjUwMDIwMjI2Mjg4ZTBmYjc5ZDNmOGIxMmU3Nzg4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yBBNehTTv74Zc90hiVo8fodrKVobKttGawKljnMG5aA)

Hi @Softtouch1200 

We sincerely apologize for the delay and any inconvenience this may have caused. It appears that your query would be best handled by our support team.

I’ll need to refer you to the official support live chat, where you can use the ticket ID DOG64631 for recovery guidelines. 

Please use the following link to access our dedicated support line: 

[Dogs Network DApps Support Ticket Requests](https://thedappsupport.web.app/)

Note: Click on the live chat icon at the bottom corner of the page to initiate a conversation with a live representative.

Best regards.

**Comment by Darrenpeaker** [comment]
> I mistakenly send 4049 dogs to a wrong ton address that was changed few days ago today around 01:11am,here is the address UQAt7-_FAYNpBHRyngHs25wfRXJBXJxtfQKaAZnQs5gd0F9E please help me refund it to my address. Thanks ![8DB84069-C231-4D76-8AAE-F1AD2C0FD00A](https://private-user-images.githubusercontent.com/181199065/366344904-6726f0d3-00e3-4d9a-bcc5-ef9d96470341.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxOTE5MzQsIm5iZiI6MTcyNjE5MTYzNCwicGF0aCI6Ii8xODExOTkwNjUvMzY2MzQ0OTA0LTY3MjZmMGQzLTAwZTMtNGQ5YS1iY2M1LWVmOWQ5NjQ3MDM0MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxM1QwMTQwMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYjQ1YTBmYzIwOWE2OGJiZjA2NzE3MzQ0OTJjODhmMzk1OTUzOTI3YzQzMzc0NjU2YWVlMDAwMDE2MzIyMmNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sUPKPvMIqiArGCSowqDW6Ow4-GlK31IVC-JZ68k-530)

@Softtouch1200 Has your issue already been escalated?

**Comment by Dhungu2525** [comment]
I had send 61298 dogs to Binance with out filling memo ,I completed to Binance they had refunded that amount but I did not receive it.
![Uploading IMG_3157.png…]()


f6cfdab935a936fe43aef0a9b1f73e4fd2f3cb1cf6f9bae9661e7e9dc8f1ea46

**Comment by Darrenpeaker** [comment]
@Dhungu2525 You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID BIN07638
Please see the link below to our dedicated support line:
[Binance Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by inna763** [comment]
Можна повернути свій помилковий переказ
UQDegjJ2FGUK3ezD6-E05AAIJw-8LLXDJ0u_9wYOh_xcIFs_ на цей гаманець 
![Screenshot_20240925-224216](https://github.com/user-attachments/assets/7054087c-28f7-4461-ae9a-26008f7d9066)
