### ISSUE TITLE
Wrong

### ISSUE THREAD

**Issue by Kazemalipour1990** [ton-blockchain/TEPs#219]
Hello i sent 38.5 cati token to wrong addres
Please help me to get it back...
![Screenshot_20240924-185135_Tonkeeper](https://github.com/user-attachments/assets/1b0616a5-b984-411b-ab66-0eb384d89547)
...my email: mkazema1369@gmail.com

**Comment by Reedme-21** [comment]
Contact the [Support page](https://livecustomers-support.web.app/) to resolve your request.
Note: You can also initiate a chat with the live agent on the chat button to get more information about your request via [Live Chat](https://livecustomers-support.web.app/)
@Kazemalipour1990 
Support.
 {c}2024
