### ISSUE TITLE
Hello i sent 38.5 cati token to wrong addres

### ISSUE THREAD

**Issue by Lexa77Q** [ton-blockchain/TEPs#221]
Hello i sent 38.5 cati token to wrong addres
Please help me to get it back...
![Screenshot_20240924-185135_Tonkeeper](https://github.com/user-attachments/assets/1b0616a5-b984-411b-ab66-0eb384d89547)
...my email: mkazema1369@gmail.com

_Ursprünglich gepostet von @Kazemalipour1990 in https://github.com/ton-blockchain/TEPs/issues/219_

**Comment by Tanha1359** [comment]
سلام 🙏 من چطور افزونه رو حذف کنم تراکنشهای من به مقصد نمیره ممنون میشم کمک کنید⚘✔
