### ISSUE TITLE
Did not receive the Coin at Binance

### ISSUE THREAD

**Issue by Bhanu474** [ton-blockchain/TEPs#224]
UQD5mxRgCuRNLxKxeOjG6r14iSroLF5FtomPnet-sgP5xI-e

I put a request for transfer of Hamster Coin to above Binance Address, but did not receive. 

Please check and try to resolve soon.

Comment "Binance hamster t"

Try this address, in case any issue:
EQD5mxRgCuRNLxKxeOjG6r14iSroLF5FtomPnet-sgP5xNJb

**Comment by mudassir12011** [comment]
Binance hamster t

**Comment by mudassir12011** [comment]
binance hamster t
