### ISSUE TITLE
Did not receive the Coin at Binance 

### ISSUE THREAD

**Issue by mudassir12011** [ton-blockchain/TEPs#229]
I put a request for transfer of Hamster Coin to above Binance Address, but did not receive.

Please check and try to resolve soon
binance address 
UQD5mxRgCuRNLxKxeOjG6r14iSroLF5FtomPnet-sgP5xI-e

**Comment by Samarsamani** [comment]
Me too 
What can I do?

**Comment by mudassir12011** [comment]
no i didn't receive
