### ISSUE TITLE
Hamster claim

### ISSUE THREAD

**Issue by Duvy10** [ton-blockchain/TEPs#231]
I didn't get my tokens on tonkeeper

**Comment by Jomossey** [comment]
@Duvy10 You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID TON07638
Please see the link below to our dedicated support line:
[Tonkeeper Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.
