### ISSUE TITLE
Wrong memo 😭

### ISSUE THREAD

**Issue by Nitheeshshelby** [ton-blockchain/TEPs#240]
![Screenshot_20240928_101450](https://github.com/user-attachments/assets/e37aded3-b315-4fb5-a678-91cb4a3548fe)

Sir i accidentally typed wrong memo instead of the memo given by the binance 
My 3380 hamster tokens gone within a second please help me 

![Screenshot_2024_0928_101437](https://github.com/user-attachments/assets/d9e017b1-bf86-42cb-92f0-fc1e14824e31)

**Comment by Anwar0911** [comment]
![Screenshot_20240929_093946](https://github.com/user-attachments/assets/947f9f1f-dbb7-4aec-830a-a6dfe4925464)

![Screenshot_20240929_093952](https://github.com/user-attachments/assets/4189b450-7eb1-46e6-aced-c42e74efc6aa)
