### ISSUE TITLE
Hamster coin lost 

### ISSUE THREAD

**Issue by Rana32233** [ton-blockchain/TEPs#242]
My con is lost , send my Hamster coin

**Comment by Rana32233** [comment]
![Screenshot_2024-09-28-10-52-28-92_a687bcbca62a390d5d520af3d0e86b1c](https://github.com/user-attachments/assets/002fb3c5-d226-4153-9810-2586f1cc74ec)

**Comment by Rana32233** [comment]
Send my Hamster coin

**Comment by Mudasirsaif** [comment]
My hamster coins lost return my coins please
