### ISSUE TITLE
Hamster kombat 

### ISSUE THREAD

**Issue by Rumbas31** [ton-blockchain/TEPs#243]
**my hamster was not received to my ton wallet but rather it's showing in ton view online and l can't withdraw or send it to anyone**

Pls help me get my hamster Kombat back

**Comment by Jomossey** [comment]
@Rumbas31 it seems like your hamster tokens weren't received in your TON wallet but are showing in TON view online, and you can't withdraw or send them?

**Comment by Rumbas31** [comment]
How can l get it back
