### ISSUE TITLE
My catizen token not received

### ISSUE THREAD

**Issue by hydraAhsan07** [ton-blockchain/TEPs#245]
I gave a ton for catizen tokens but I neither got a ton nor a catizen token

**Comment by Mamad3426m** [comment]
/

**Comment by Mamad3426m** [comment]
> من یک تن برای ژتون های کاتیزن دادم اما نه یک تن گرفتم و نه یک توکن کاتیزن

**Comment by Mamad3426m** [comment]
> /

من کتیزن دریافت نشد یعنی چه
