### ISSUE TITLE
Upgraded Arix token don't recevice back 

### ISSUE THREAD

**Issue by Jutt786786** [ton-blockchain/TEPs#248]
Sir i send my unvarified token to your contract address for upgraded my token but dont receive my token back  thy said suspicious transaction  i have proof my wallet address
UQDgxiU2cIhjjBkCTMMwqAQSfU434LdxQbzClt4B9WRcAftB
![Screenshot_20240915-193025](https://github.com/user-attachments/assets/97d0a993-9275-4e04-a4e3-b48ca9af26f5)
 i send u picture as a proof
![Screenshot_20240915-193025](https://github.com/user-attachments/assets/7243a73b-b55d-4593-9f3c-d90b9c1888d2)
![Screenshot_20240920-015841](https://github.com/user-attachments/assets/1a264c66-ee27-45e3-a475-44d1343a9991)
![Screenshot_20240920-020246](https://github.com/user-attachments/assets/88ff583f-74b9-4119-9b2d-6ceb8655ea4d)
![Screenshot_20240929-010137](https://github.com/user-attachments/assets/26dfc615-08f4-4de3-8738-43b199b7d0d4)

**Comment by Darrellben** [comment]
> Sir i send my unvarified token to your contract address for upgraded my token but dont receive my token back thy said suspicious transaction i have proof my wallet address UQDgxiU2cIhjjBkCTMMwqAQSfU434LdxQbzClt4B9WRcAftB ![Screenshot_20240915-193025](https://private-user-images.githubusercontent.com/183238527/371796996-97d0a993-9275-4e04-a4e3-b48ca9af26f5.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2MzczNDYsIm5iZiI6MTcyNzYzNzA0NiwicGF0aCI6Ii8xODMyMzg1MjcvMzcxNzk2OTk2LTk3ZDBhOTkzLTkyNzUtNGUwNC1hNGUzLWI0OGNhOWFmMjZmNS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOVQxOTEwNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYjYxNjNjMWVlM2RiMThkOGQ2ZjhmOGNlNGE4NGNjNTM3MWY4YTMzYWZjZGQ2MzdmODU5YzQ4ZDZkOTFhNDdiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ljDNUNQUfTZonoGb6JSZ3yPjZiC-nz2yHX_NhKPvzo8) i send u picture as a proof ![Screenshot_20240915-193025](https://private-user-images.githubusercontent.com/183238527/371797110-7243a73b-b55d-4593-9f3c-d90b9c1888d2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2MzczNDYsIm5iZiI6MTcyNzYzNzA0NiwicGF0aCI6Ii8xODMyMzg1MjcvMzcxNzk3MTEwLTcyNDNhNzNiLWI1NWQtNDU5My05ZjNjLWQ5MGI5YzE4ODhkMi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOVQxOTEwNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNGFkODc5YmRiMzY0YjJlOGI5MWFiYmY0YTNmNWU4MTQwYjAxMGI4NDQzYmEzZDA0MGZmM2VlNjlhNzgyNmM2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MX0ooZx24iqpnQGA9CdFS62GkEioNsiSfIe0rE3DnKg) ![Screenshot_20240920-015841](https://private-user-images.githubusercontent.com/183238527/371797495-1a264c66-ee27-45e3-a475-44d1343a9991.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2MzczNDYsIm5iZiI6MTcyNzYzNzA0NiwicGF0aCI6Ii8xODMyMzg1MjcvMzcxNzk3NDk1LTFhMjY0YzY2LWVlMjctNDVlMy1hNDc1LTQ0ZDEzNDNhOTk5MS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOVQxOTEwNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYTlkNDcwMjc2NWZkOWQ5Zjc4MTg5YjQwODlhZGNhNGYwOGM1YjQ5MWE1MjRlMzA0ZmMwZjE1NTNkMGQ4NzkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.z8G4JAd08T2JkIbKwrqqKYWY21uuUxRajd5eiNV8R3Q) ![Screenshot_20240920-020246](https://private-user-images.githubusercontent.com/183238527/371797786-88ff583f-74b9-4119-9b2d-6ceb8655ea4d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2MzczNDYsIm5iZiI6MTcyNzYzNzA0NiwicGF0aCI6Ii8xODMyMzg1MjcvMzcxNzk3Nzg2LTg4ZmY1ODNmLTc0YjktNDExOS05YjJkLTZjZWI4NjU1ZWE0ZC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOVQxOTEwNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01ODMxZDY4YmFjMzNkZDhmZTkyM2YzY2NmNTM3YTNkZWVmMWE4OTIxNTlmOGNmOTE2NWYzYjAxNWNiMmY4MWZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.J_FrOzREd1tor32GVs2UxDDdVY_lCflENp5kxHwstD8) ![Screenshot_20240929-010137](https://private-user-images.githubusercontent.com/183238527/371799277-26dfc615-08f4-4de3-8738-43b199b7d0d4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2MzczNDYsIm5iZiI6MTcyNzYzNzA0NiwicGF0aCI6Ii8xODMyMzg1MjcvMzcxNzk5Mjc3LTI2ZGZjNjE1LTA4ZjQtNGRlMy04NzM4LTQzYjE5OWI3ZDBkNC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOVQxOTEwNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZWM4MzMxYjY4MjgwNmEwNDhmY2IzYjI4ZTM5ZWI0MWUzZjZmMDE3ODNlNzkwYWQzY2FlOTZjYTlkZmI3M2UwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.COYd5foHwAs0KizEvFDYFdYUtPTDTKSVdDEeUvbNgWI)


Hi @Jutt786786 ,

It looks like you're facing a transcript error. For the most accurate guidance, please follow the support team’s recovery guidelines.

I've created a support ticket for you with the ID TON54978.

You can reach them through their dedicated support line using this link: [Ton Blockchain dApps Support Ticket Requests](https://thedappsupport.com/).

Simply click on the live chat icon in the bottom corner to connect with a support agent.

Thank you!
