### ISSUE TITLE
An NFT was sent from my wallet to Rang Wallet Address Number by mistake

### ISSUE THREAD

**Issue by Alaminjp** [ton-blockchain/TEPs#249]
Please return my NFT 
 wallet address :
UQBrjeF_cS6-cR-618-qif29AEObx2IDN_Q3WMp8A3w5CGi 
![Screenshot_20240929_040526](https://github.com/user-attachments/assets/51ab9c6e-e9e0-4a1f-b813-6460a2ef3331)
1

**Comment by Jomossey** [comment]
@Alaminjp You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID NFT07638
Please see the link below to our dedicated support line:
[NFT Network DApps Support Ticket Requests.](https://thedappsupport.com/) Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.
