### ISSUE TITLE
EQBJ_X3ysvgOGUo6XB3eUTCvagarGeA3X-QD3lxSqZzQbQ4w

### ISSUE THREAD

**Issue by Pablocuer01** [ton-blockchain/TEPs#265]
EQBJ_X3ysvgOGUo6XB3eUTCvagarGeA3X-QD3lxSqZzQbQ4w

_Originally posted by @Josepthande in https://github.com/ton-blockchain/TEPs/issues/262#issuecomment-2386625964_

**Comment by Josepthande** [comment]
How do i withdraw
