### ISSUE TITLE
Ton transaction 

### ISSUE THREAD

**Issue by odogwufreaky** [ton-blockchain/TEPs#279]
UQAt8CWu6Vs1ghgFsV0V2XdZ-Yps473XYhnITbPQKueuclxo

0:2df025aee95b35821805b15d15d97759f98a6ce3bdd76219c84db3d02ae7ae72

**Comment by EhsanMousazadeh** [comment]
معامله من failed شد ولی موجودی هم رفت؟

**Comment by EhsanMousazadeh** [comment]
چرا اینطوریه تون کیپر معاملات فیلد می‌کنه 
داگزها رفتن xmpire  هام رفتن ....چه وضعیه...
چرا قابل برگشت نیستن معاملات ناموفق ایمن مثلا
