### ISSUE TITLE
Didnt received tokens

### ISSUE THREAD

**Issue by Heaidar** [ton-blockchain/TEPs#293]
Hello.
I was supposed to have 228,500 CATS tokens.  But I haven't received any. I also have payed the fee . Please do what is needed . 
![Screenshot_۲۰۲۴۱۰۱۸_۲۲۵۴۰۶_Telegram](https://github.com/user-attachments/assets/599c3b2a-aa72-4201-9810-c5bccb251382)

**Comment by JohnnyGoGoGo** [comment]
Not a suitable place. Please contact technical support of the service you are using.
