### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by Bams166** [ton-blockchain/TEPs#312]
query_id: 6083770390218087000
amount: "31511000000000"
sender: 0:987d510c6919aedf315805a70a3286381f88faebf2505730436931d24f728815
forward_payload:
  is_right: true
  value:
    sum_type: TextComment
    op_code: 0
    value:
      text: "X empire "

**Comment by AfeworkShalom09** [comment]
> query_id: 6083770390218087000
> amount: "31511000000000"
> sender: 0:987d510c6919aedf315805a70a3286381f88faebf2505730436931d24f728815
> forward_payload:
>   is_right: true
>   value:
>     sum_type: TextComment
>     op_code: 0
>     value:
>       text: "X empire "

Please unclose my gifts

**Comment by Bams166** [comment]
Is there a way to solve this issue

**Comment by JohnnyGoGoGo** [comment]
Not a suitable place. Please contact technical support of the service you are using.
