### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by mziyassine** [ton-blockchain/TEPs#342]
I lost my 24 recovery words tonhube wallet but I still have the address of wallet

**Comment by Annawoody** [comment]
The address alone isn't enough to regain access.I'll have to refer you to the official support live chat with the ticket ID TON07638
Please see the link below to our dedicated support line:
[Tonhub Network DApps Support Ticket Requests.](https://thedappsupport.com/
)
 Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.
@mziyassine

**Comment by JohnnyGoGoGo** [comment]
If you have a wallet address but no 24 secret words, you will not get access to the wallet.
