### ISSUE TITLE
> > text: Receive 0.14 TON + 100 USDT

### ISSUE THREAD

**Issue by Hamed1370m** [ton-blockchain/TEPs#343]
> > text: Receive 0.14 TON + 100 USDT

_Originally posted by @LuCaSiNo40 in https://github.com/ton-blockchain/TEPs/issues/119#issuecomment-2451737911_

**Comment by Hamed1370m** [comment]
/

>           > > text: Receive 0.14 TON + 100 USDT
> ```
> 
> _در اصل توسط@LuCaSiNo40در [شماره 119 (نظر)](https://github.com/ton-blockchain/TEPs/issues/119#issuecomment-2451737911)_

**Comment by Addisalem243** [comment]
100ton not sent but minus from my wallet ton

**Comment by Addisalem243** [comment]
Where is the reward

**Comment by Addisalem243** [comment]
Where is my ton from reward  it is fake

**Comment by AfeworkShalom09** [comment]
That was fack it says '0.000001 Not "
