### ISSUE TITLE
Refund my money please 

### ISSUE THREAD

**Issue by Berrydc042** [ton-blockchain/TEPs#344]
![IMG_2536](https://github.com/user-attachments/assets/e0251282-bb0a-4f3f-aadc-d82e6eb512b7)
![IMG_2537](https://github.com/user-attachments/assets/2cede9ae-ec48-4d99-a165-4aee0340a2d7)
![IMG_2535](https://github.com/user-attachments/assets/16868139-7424-45d3-bfbc-85c8caaf0c41)

**Comment by JohnnyGoGoGo** [comment]
Not a suitable place. Please contact technical support of the service you are using.

**Comment by Berrydc042** [comment]
How can I contact them please help me
