### ISSUE TITLE
Ton

### ISSUE THREAD

**Issue by Admi64** [ton-blockchain/TEPs#346]
Случайно провел Транзакцию .Не могл бы мне обрано перевести Ton 
![Безымянный](https://github.com/user-attachments/assets/14e4eb06-98f9-4e5f-9364-2fe436447a76)

**Comment by Admi64** [comment]
UQDJ2vdRNzgWC5zll9yJif18vP3aNiO_fvdzWH2x6M2P3ekX

**Comment by JohnnyGoGoGo** [comment]
Не подходящее место. Обратитесь в службу технической поддержки используемого вами сервиса.
