### ISSUE TITLE
Got scammed

### ISSUE THREAD

**Issue by Hmoudi4147** [ton-blockchain/TEPs#360]
I got scammed by the holder of this address EQAkvTiwwH1ScZlEtu7W3z_AsY3RJcmCRkImzgZEwAMaXxDA
Transaction hash: 5e1dda3be5053326828b32c091ac45d62b05902ac6158b9f9dca58fb23b21d59

**Comment by JohnnyGoGoGo** [comment]
Not a suitable place. Please contact technical support of the service you are using.

**Comment by Tech-gem98** [comment]
Contact SAFERECOVERY98 @ TELEGRAMM for assistance of recovery
