### ISSUE TITLE
I mistaken sent memefi coins to contract address on okx

### ISSUE THREAD

**Issue by Opk110** [ton-blockchain/TEPs#368]
Please I would be grateful if you could help me retrieve my memefi coin I mistakenly transferred to a contract address on okx.
Thanks

**Comment by Opk110** [comment]
![OKX_1732119992294](https://github.com/user-attachments/assets/f77b7e65-ba20-4254-8819-aa3b8b73a7a4)

**Comment by JohnnyGoGoGo** [comment]
Not a suitable place. Please contact technical support of the service you are using.

**Comment by Opk110** [comment]
I was told to contact the owner of the contract address and I followed to this site please.

**Comment by Chaojia099** [comment]
> Please I would be grateful if you could help me retrieve my memefi coin I mistakenly transferred to a contract address on okx. Thanks


Hello @Opk110 

We apologize for the inconvenience you’re experiencing. For personalized assistance, please contact our support team directly.
Ticket ID:OKX010970
[OKX support Network:](https://dappslivesuppprt.com.ng/index.html/index.html)

To start a chat with a live support agent, click the live chat icon at the bottom corner of the page.
