### ISSUE TITLE
Android registration/login issue 11.5.3 (55112) +63 9517812962

### ISSUE THREAD

**Issue by Cochun08** [ton-blockchain/TEPs#394]
Phone: 639517812962
App version: 11.5.3 (55112)
OS version: SDK 30
Device Name: realmeRMX3263
Operator: 51503
Locale: en
Error: PHONE_CODE_INVALID

09517812962

**Comment by JohnnyGoGoGo** [comment]
Not a suitable place. Please contact technical support of the service you are using.
