### ISSUE TITLE
> menerima 0,14 ton + 100$

### ISSUE THREAD

**Issue by Hayk7777777** [ton-blockchain/TEPs#398]
> menerima 0,14 ton + 100$
> 
> Nomor telepon 773181909 🆔 55111321

_Originally posted by @Imamghozali45 in https://github.com/ton-blockchain/TEPs/issues/119#issuecomment-2498569104_

**Comment by Meysamchz** [comment]
UQA4dmvxpABrOVIvtBEwwpMNSQVjdiTYuEbVJiL870xqwTzZ

**Comment by Hayk7777777** [comment]
> ```
>           > menerima 0,14 ton + 100$
> ```
> 
> > Nomor telepon 773181909 🆔 55111321
> 
> _Originally posted by @Imamghozali45 in [#119 (comment)](https://github.com/ton-blockchain/TEPs/issues/119#issuecomment-2498569104)_
